### PR TITLE
Feat take action 11 block list

### LINKED ISSUE #11: Block list
### User story
As a repo admin, I want to block specific usernames from being able to assign an issue to themselves, so that my bot accounts can tell human contributors to use the take-action command without assigning the issue to a bot.

### Requirement
Allow users to provide a block list to prevent specific GitHub usernames from self-assigning issues.

### PR DESCRIPTION
**Pull request by jamesgeddes**
Add the block-list variable and use it in a leading guard clause. This ensures that nothing further will run if the triggering login name is found in the block list. Provide back-compatible default.

Tidy the code slightly by converting the nested if statements to negative guard clauses with multiple exits. This makes the code more legible.

Finally, rename ISSUE_CURRENTLY_ASSIGNED to ISSUE_AWAITING_ASSIGNMENT to clarify usage. Previously, ISSUE_CURRENTLY_ASSIGNED=true would then assign the issue to the user, which is counterintuitive.

resolve #11

### CODE REVIEW

**Comment by jamesgeddes** [comment]
Hey @bdougie I don't suppose you have had a chance to think about any feedback on this, have you? Thanks!

**Comment by bdougie** [comment]
Hey @jamesgeddes sorry for the delay. So far looks good, just need to test it locally myself.

**Review by bdougie — APPROVED** [review]
LGTM

**Comment by jamesgeddes** [comment]
Thanks @bdougie

**Pull request merged**
